### ISSUE TITLE
[Bug]: Cant make plugin to work [base path does not exist and other errors]

### ISSUE THREAD

**Issue by victordra** [Vinzent03/obsidian-git#755]
### Describe the bug

I have installed Obsidian 1.6.7, Obisidian Git, git 2.41.0.windows.2
Where git says:
C:\Program Files\Git\cmd\git.exe
C:\Program Files\Git\mingw64\bin\git.exe
C:\Program Files\Git\bin\git.exe
I have created a vault in folder
C:\Users\xxx\Desktop\diy\stuf
I have added a .gitignore with the .obsidian and .gitignore listed.
I have created a repository in the same folder.
Push, commit, and remote push work from git. 
Configuration of obsidian git plugin: 
git binary path is set to one of the three listed by where git (see above). Tryed all combinations with or without "".
Costum base path and custom git directory is set to  
C:\Users\xxx\Desktop\diy\stuf\. Tryed all combinations with or without "", with or without \ at the end.
Sorry for bad english/formating. First bug report for me. Tried to list all available data.
Thank you in advance.

### Relevant errors (if available) from notifications or console (`CTRL+SHIFT+I`)

```shell
top of settings page it says: git is not ready. when all settings are correct you can configure auto backup, etc. This does not change.

*****************

Different base path for git binary configurations and errors

***************
without quotation marks I get this message in upper right corner of screen but no errors in With ctrl + shift + i: Obsidiangit: base path does not exist

*****************
with quotation marks i get no message in upper right corner of screen but the following With ctrl + shift + i: 
Error: spawnSync C:\Program Files\Git\cmd\git.exe~ ENOENT
    at Object.spawnSync (node:internal/child_process:1124:20)
    at spawnSync (node:child_process:891:24)
    at SimpleGit.isGitInstalled (plugin:obsidian-git:30384:57)
    at SimpleGit.setGitInstance (plugin:obsidian-git:29730:14)
    at SimpleGit.updateGitPath (plugin:obsidian-git:30333:10)
    at eval (plugin:obsidian-git:32768:29)
    at t.onChanged (app.js:1:1487413)
isGitInstalled @ plugin:obsidian-git:30392
plugin:obsidian-git:30392 Error: spawnSync {C:\Program Files\Git\cmd\git.exe~ ENOENT
    at Object.spawnSync (node:internal/child_process:1124:20)
    at spawnSync (node:child_process:891:24)
    at SimpleGit.isGitInstalled (plugin:obsidian-git:30384:57)
    at SimpleGit.setGitInstance (plugin:obsidian-git:29730:14)
    at SimpleGit.updateGitPath (plugin:obsidian-git:30333:10)
    at eval (plugin:obsidian-git:32768:29)
    at t.onChanged (app.js:1:1487413)
isGitInstalled @ plugin:obsidian-git:30392
plugin:obsidian-git:30392 Error: spawnSync C:\Program Files\Git\cmd\git.exe~ ENOENT
    at Object.spawnSync (node:internal/child_process:1124:20)
    at spawnSync (node:child_process:891:24)
    at SimpleGit.isGitInstalled (plugin:obsidian-git:30384:57)
    at SimpleGit.setGitInstance (plugin:obsidian-git:29730:14)
    at SimpleGit.updateGitPath (plugin:obsidian-git:30333:10)
    at eval (plugin:obsidian-git:32768:29)
    at t.onChanged (app.js:1:1487413)
isGitInstalled @ plugin:obsidian-git:30392
plugin:obsidian-git:30392 Error: spawnSync }C:\Program Files\Git\cmd\git.exe~ ENOENT
    at Object.spawnSync (node:internal/child_process:1124:20)
    at spawnSync (node:child_process:891:24)
    at SimpleGit.isGitInstalled (plugin:obsidian-git:30384:57)
    at SimpleGit.setGitInstance (plugin:obsidian-git:29730:14)
    at SimpleGit.updateGitPath (plugin:obsidian-git:30333:10)
    at eval (plugin:obsidian-git:32768:29)
    at t.onChanged (app.js:1:1487413)
isGitInstalled @ plugin:obsidian-git:30392
plugin:obsidian-git:30392 Error: spawnSync C:\Program Files\Git\cmd\git.exe~ ENOENT
    at Object.spawnSync (node:internal/child_process:1124:20)
    at spawnSync (node:child_process:891:24)
    at SimpleGit.isGitInstalled (plugin:obsidian-git:30384:57)
    at SimpleGit.setGitInstance (plugin:obsidian-git:29730:14)
    at SimpleGit.updateGitPath (plugin:obsidian-git:30333:10)
    at eval (plugin:obsidian-git:32768:29)
    at t.onChanged (app.js:1:1487413)
isGitInstalled @ plugin:obsidian-git:30392
plugin:obsidian-git:30392 Error: spawnSync "C:\Program Files\Git\cmd\git.exe~ ENOENT
    at Object.spawnSync (node:internal/child_process:1124:20)
    at spawnSync (node:child_process:891:24)
    at SimpleGit.isGitInstalled (plugin:obsidian-git:30384:57)
    at SimpleGit.setGitInstance (plugin:obsidian-git:29730:14)
    at SimpleGit.updateGitPath (plugin:obsidian-git:30333:10)
    at eval (plugin:obsidian-git:32768:29)
    at t.onChanged (app.js:1:1487413)
isGitInstalled @ plugin:obsidian-git:30392
plugin:obsidian-git:30392 Error: spawnSync "C:\Program Files\Git\cmd\git.exe ENOENT
    at Object.spawnSync (node:internal/child_process:1124:20)
    at spawnSync (node:child_process:891:24)
    at SimpleGit.isGitInstalled (plugin:obsidian-git:30384:57)
    at SimpleGit.setGitInstance (plugin:obsidian-git:29730:14)
    at SimpleGit.updateGitPath (plugin:obsidian-git:30333:10)
    at eval (plugin:obsidian-git:32768:29)
    at t.onChanged (app.js:1:1487413)
isGitInstalled @ plugin:obsidian-git:30392
plugin:obsidian-git:30392 Error: spawnSync "C:\Program Files\Git\cmd\git.exe" ENOENT
    at Object.spawnSync (node:internal/child_process:1124:20)
    at spawnSync (node:child_process:891:24)
    at SimpleGit.isGitInstalled (plugin:obsidian-git:30384:57)
    at SimpleGit.setGitInstance (plugin:obsidian-git:29730:14)
    at SimpleGit.updateGitPath (plugin:obsidian-git:30333:10)
    at eval (plugin:obsidian-git:32768:29)
    at t.onChanged (app.js:1:1487413)
isGitInstalled @ plugin:obsidian-git:30392
plugin:obsidian-git:30392 Error: spawnSync "C:\Program Files\Git\cmd\git.exe" ENOENT
    at Object.spawnSync (node:internal/child_process:1124:20)
    at spawnSync (node:child_process:891:24)
    at SimpleGit.isGitInstalled (plugin:obsidian-git:30384:57)
    at SimpleGit.setGitInstance (plugin:obsidian-git:29730:14)
    at eval (plugin:obsidian-git:32795:29)
    at HTMLButtonElement.<anonymous> (app.js:1:1484574)
isGitInstalled @ plugin:obsidian-git:30392

*************************
Different repository path settings
ctrl + p commands (git ignore works) all other commands: 
without quotation marks: cant find a valid git repository. please create one via the given command or clone an existing `repo`
with quotation marks: cant run git command
without \ at the end: cant run git command
```

### Steps to reproduce

Configuration steps listed above

### Expected Behavior

Eliminate errors.
Work as in istalation guide.

### Operating system

Windows

### Installation Method

None

### Plugin version

2.25.0

**Comment by Vinzent03** [comment]
Please try to leave the custom base path and custom git dir directory settings empty. You should be able to leave the git binary path empty as well, but this depends on your PATH settings.
